baseURL = "https://dev-log.prefect.io"
theme = 'hugo-bearblog'

title = "Prefect Dev Log"
author = "Prefect Engineering Team"
copyright = "Copyright © 2025, Prefect Technologies Inc."
languageCode = "en-US"

enableRobotsTXT = true

disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]

[permalinks]
blog = "/:slug/"
tags = "/blog/:slug"

[params]
description = "Create with :heart: by Prefect"
title = "Prefect Dev Log"
enablePostNavigator = true
favicon = "images/favicon.png"

[markup]
[markup.highlight]
noClasses = false
lineNos = true
lineNumbersInTable = false
codeFences = true
