baseURL = "https://example.com"
theme = 'hugo-bearblog'

title = "Prefect Dev Log"
author = "Prefect Engineering Team"
copyright = "Copyright © 2025, Prefect Technologies Inc."
languageCode = "en-US"

enableRobotsTXT = true

disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]
[permalinks]
blog = "/:slug/"
tags = "/blog/:slug"

[params]
description = "Create with :heart: by Prefect"
title = "Prefect Dev Log"
enablePostNavigator = true
hideMadeWithLine = true
favicon = "images/favicon.png"

[markup]
[markup.highlight]
style = 'friendly'
lineNos = true
lineNumbersInTable = false
codeFences = true
